server:
  port: 8001
spring:
  application:
    name: eureka
  security:
    user:
      name: lxd
      password: 123456
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    hostname: localhost
